// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionSummary = {
  id: string;
  source: string;
  title: string;
  firstUserMessage: string | null;
  cwd: string | null;
  cwdShort: string | null;
  messageCount: number;
  tokensTotal: number | null;
  model: string | null;
  lastActivity: string | null;
  startedAt: string | null;
  hidden: boolean;
  isRunning: boolean;
};
