// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillSummary = { id: string, name: string, source: string, marketplace: string | null, description: string | null, triggers: Array<string>, cliCommands: Array<string>, symlinkTo: string | null, fileSize: number, filePath: string, };
