import type { TimelineEntry } from "./chat-session-store";

export type ExportFormat = "markdown" | "html";

export interface ExportMeta {
  title?: string;
  model?: string;
  cwd?: string;
  startedAt?: string;
  exportedAt: string;
}

export function buildConversationMarkdown(
  timeline: TimelineEntry[],
  meta: ExportMeta
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${meta.title || "Conversation"}`);
  lines.push("");
  if (meta.model) lines.push(`**Model:** ${meta.model}`);
  if (meta.cwd) lines.push(`**Project:** \`${meta.cwd}\``);
  if (meta.startedAt) lines.push(`**Started:** ${meta.startedAt}`);
  lines.push(`**Exported:** ${meta.exportedAt}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const entry of timeline) {
    switch (entry.kind) {
      case "user":
        lines.push("## User");
        lines.push("");
        lines.push(entry.text);
        lines.push("");
        lines.push("---");
        lines.push("");
        break;

      case "assistant":
        lines.push("## Assistant");
        lines.push("");
        if (entry.thinkingText) {
          lines.push("<details>");
          lines.push("<summary>Thinking</summary>");
          lines.push("");
          lines.push(entry.thinkingText);
          lines.push("");
          lines.push("</details>");
          lines.push("");
        }
        lines.push(entry.text);
        lines.push("");
        lines.push("---");
        lines.push("");
        break;

      case "tool": {
        lines.push(`### Tool: ${entry.toolName}`);
        lines.push("");
        if (entry.input) {
          lines.push("**Input:**");
          lines.push("```json");
          lines.push(tryFormatJson(entry.input));
          lines.push("```");
          lines.push("");
        }
        if (entry.output) {
          const label = entry.isError ? "Error" : "Output";
          lines.push(`**${label}:**`);
          lines.push("```");
          const truncated =
            entry.output.length > 5000
              ? entry.output.slice(0, 5000) + "\n... (truncated)"
              : entry.output;
          lines.push(truncated);
          lines.push("```");
          lines.push("");
        }
        lines.push("---");
        lines.push("");
        break;
      }

      case "system":
        lines.push(`*${entry.text}*`);
        lines.push("");
        break;
    }
  }

  return lines.join("\n");
}

export function buildConversationHtml(
  markdown: string,
  meta: ExportMeta
): string {
  const title = meta.title || "Conversation Export";
  const htmlBody = markdownToSimpleHtml(markdown);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #1a1a1a; background: #fff; }
h1 { font-size: 1.5rem; border-bottom: 2px solid #e5e5e5; padding-bottom: 0.5rem; }
h2 { font-size: 1.1rem; margin-top: 2rem; color: #333; }
h3 { font-size: 0.95rem; color: #555; }
hr { border: none; border-top: 1px solid #e5e5e5; margin: 1.5rem 0; }
code { background: #f4f4f5; padding: 0.15em 0.4em; border-radius: 3px; font-size: 0.9em; }
pre { background: #f4f4f5; padding: 1rem; border-radius: 6px; overflow-x: auto; font-size: 0.85em; }
pre code { background: none; padding: 0; }
details { margin: 0.5rem 0; padding: 0.5rem; background: #f9fafb; border-radius: 6px; }
summary { cursor: pointer; font-weight: 500; color: #666; }
strong { color: #333; }
.meta { color: #666; font-size: 0.85rem; }
</style>
</head>
<body>
${htmlBody}
<footer style="margin-top:3rem;padding-top:1rem;border-top:1px solid #e5e5e5;font-size:0.8rem;color:#999;">
Generated by Agent Panel &middot; ${escapeHtml(meta.exportedAt)}
</footer>
</body>
</html>`;
}

export function downloadTextFile(
  filename: string,
  content: string,
  mimeType: string
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function printHtmlAsPdf(html: string): void {
  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.left = "-9999px";
  iframe.style.top = "-9999px";
  document.body.appendChild(iframe);

  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (doc) {
    doc.open();
    doc.write(html);
    doc.close();
    setTimeout(() => {
      iframe.contentWindow?.print();
      setTimeout(() => document.body.removeChild(iframe), 1000);
    }, 250);
  }
}

function tryFormatJson(input: string): string {
  try {
    return JSON.stringify(JSON.parse(input), null, 2);
  } catch {
    return input;
  }
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function markdownToSimpleHtml(md: string): string {
  return md
    .replace(/^### (.*$)/gm, "<h3>$1</h3>")
    .replace(/^## (.*$)/gm, "<h2>$1</h2>")
    .replace(/^# (.*$)/gm, "<h1>$1</h1>")
    .replace(/^---$/gm, "<hr>")
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/```(\w*)\n([\s\S]*?)```/g, "<pre><code>$2</code></pre>")
    .replace(/<details>/g, "<details>")
    .replace(/<\/details>/g, "</details>")
    .replace(/<summary>(.*?)<\/summary>/g, "<summary>$1</summary>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(?!<[hpuold])/gm, "<p>")
    .replace(/<p><\/p>/g, "");
}
