version: 2
updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    labels: [dependencies, frontend]
    groups:
      frontend-deps:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: cargo
    directory: /src-server
    schedule:
      interval: weekly
    labels: [dependencies, backend]
    groups:
      backend-deps:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies, actions]
    commit-message:
      prefix: "ci(deps)"
